### ISSUE TITLE
ValueError: No tables found

### ISSUE THREAD

**Issue by boulderphd** [financedata-org/FinanceDataReader#122]
안녕하세요. 늘 감사하게 잘 사용하고 있습니다.

어제(3/15) 오후부터 다음과 같은 error가 발생합니다.  특히, 지수값과 외국 종목 값에서 발생합니다.

확인을 부탁드립니다. 감사합니다.  당연히 새 버전으로 fdr을 update했습니다.  update한 뒤에도 같은 현상입니다.

감사합니다. 

==

import FinanceDataReader as fdr
fdr.DataReader('KS11', '2020')

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-6c5c93160864>", line 3, in <module>
    fdr.DataReader('KS11', '2020')
  File "C:\ProgramData\Anaconda3\lib\site-packages\FinanceDataReader\data.py", line 41, in DataReader
    df = reader(symbol, start, end, exchange, data_source).read()
  File "C:\ProgramData\Anaconda3\lib\site-packages\FinanceDataReader\investing\data.py", line 83, in read
    dfs = pd.read_html(StringIO(r.text))
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\util\_decorators.py", line 296, in wrapper
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\html.py", line 1086, in read_html
    return _parse(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\html.py", line 917, in _parse
    raise retained
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\html.py", line 898, in _parse
    tables = p.parse_tables()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\html.py", line 217, in parse_tables
    tables = self._parse_tables(self._build_doc(), self.match, self.attrs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\html.py", line 547, in _parse_tables
    raise ValueError("No tables found")
ValueError: No tables found

**Comment by FinanceData** [comment]
https://github.com/FinanceData/FinanceDataReader/issues/133 으로 정리하였습니다.

**Comment by FinanceData** [comment]
2022-09-23 [Release Note 0.9.40](https://github.com/financedata-org/FinanceDataReader/wiki/Release-Note-0.9.40) 에서 FIX 하였습니다
